on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      sha:
        description: 'Commit sha that should be used to link to PR'
        required: true

jobs:
  attach-to-pr:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ inputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ inputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
