on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_related_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
